# Generated by Django 3.2.16 on 2025-04-20 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=50)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Iva',
            fields=[
                ('id_iva', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=10)),
            ],
            options={
                'verbose_name': 'Iva',
                'verbose_name_plural': 'Ivas',
                'db_table': 'iva',
            },
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id_medida', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=100)),
                ('prefijo', models.CharField(db_column='prefijo', max_length=20)),
            ],
            options={
                'verbose_name': 'Medida',
                'verbose_name_plural': 'Medidas',
                'db_table': 'medidas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('precio_actual', models.FloatField(db_column='precio_actual')),
                ('stock_minimo', models.IntegerField(db_column='stock_minimo', null=True)),
                ('stock_actual', models.IntegerField(db_column='stock_actual', null=True)),
                ('vencimiento', models.DateField(db_column='vencimiento', null=True)),
                ('costo_actual', models.FloatField(db_column='costo_actual', null=True)),
                ('usuario_creacion', models.IntegerField(db_column='usuario_creacion', null=True)),
                ('usuario_modificacion', models.IntegerField(db_column='usuario_modificacion', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_modificacion', models.DateTimeField(db_column='fecha_modificacion', null=True)),
                ('id_iva', models.ForeignKey(db_column='id_iva', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.iva')),
                ('id_medida', models.ForeignKey(db_column='id_medida', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.medida')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id_tipo_producto', models.AutoField(primary_key=True, serialize=False)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.categoria')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.producto')),
            ],
            options={
                'verbose_name': 'CategoriaProducto',
                'verbose_name_plural': 'CategoriasProductos',
                'db_table': 'categoria_producto',
            },
        ),
    ]
