# Generated by Django 3.2.16 on 2026-03-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_pedidos_ya',
            field=models.FloatField(blank=True, db_column='precio_pedidos_ya', default=0, null=True),
        ),
    ]
