# Generated by Django 5.2.9 on 2026-03-22 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_precio_pedidos_ya'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_pedidos_ya',
        ),
    ]
