# Generated by Django 3.2.16 on 2025-04-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.CharField(db_column='documento', max_length=16)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('apellido', models.CharField(db_column='apellido', max_length=100)),
                ('correo', models.CharField(db_column='correo', max_length=100)),
                ('celular', models.CharField(db_column='celular', max_length=50)),
                ('direccion', models.CharField(db_column='direccion', max_length=255, null=True)),
                ('estado', models.CharField(db_column='estado', max_length=16, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
            },
        ),
    ]
