# Generated by Django 3.2.16 on 2025-12-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='cant_chico',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='cant_grande',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='tipo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
