# Generated by Django 3.2.16 on 2025-12-28 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20251228_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='tipo',
        ),
    ]
