# Generated by Django 3.2.16 on 2025-12-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20251228_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cant_chico',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cant_grande',
            field=models.IntegerField(default=0),
        ),
    ]
