# Generated by Django 3.2.16 on 2026-03-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_produccion_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producciondiaria',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='producciondiaria',
            name='estado',
            field=models.CharField(choices=[('CREADO', 'Creado'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado')], default='CREADO', max_length=10),
        ),
        migrations.AlterModelOptions(
            name='producciondiaria',
            options={'ordering': ['-fecha', '-fecha_creacion']},
        ),
    ]
