# Generated by Django 5.2.9 on 2026-03-22 00:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_precio_pedidos_ya'),
        ('inventario', '0006_produccion_estado_y_fecha_no_unica'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProduccionDetalle',
        ),
        migrations.DeleteModel(
            name='ProduccionDiaria',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.CreateModel(
            name='MovimientoProducto',
            fields=[
                ('id_movimiento', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('cantidad', models.IntegerField(default=0)),
                ('stock_anterior', models.IntegerField(default=0)),
                ('stock_posterior', models.IntegerField(default=0)),
                ('fecha_movimiento', models.DateTimeField(default=django.utils.timezone.now)),
                ('referencia', models.CharField(blank=True, default='', max_length=100)),
                ('observacion', models.TextField(blank=True, default='')),
                ('usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Movimiento de producto',
                'verbose_name_plural': 'Movimientos de productos',
                'db_table': 'movimiento_producto',
                'ordering': ['-fecha_movimiento', '-id_movimiento'],
            },
        ),
    ]
