# Generated by Django 3.2.16 on 2026-03-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=150)),
                ('ruc', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('nro_timbrado', models.CharField(max_length=30)),
                ('vigencia_timbrado_desde', models.DateField()),
                ('vigencia_timbrado_hasta', models.DateField()),
                ('establecimiento', models.CharField(default='001', max_length=3)),
                ('punto_expedicion', models.CharField(default='001', max_length=3)),
                ('secuencia_actual', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Configuracion de Empresa',
                'verbose_name_plural': 'Configuracion de Empresa',
                'db_table': 'configuracion_empresa',
            },
        ),
    ]
