# Generated by Django 3.2.16 on 2025-04-20 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0001_initial'),
        ('tipo_pago', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, db_column='fecha_venta')),
                ('total_iva_10', models.FloatField(db_column='total_iva_10')),
                ('total_iva_5', models.FloatField(db_column='total_iva_5')),
                ('total_venta', models.FloatField(db_column='total_venta')),
                ('usuario_creacion', models.BigIntegerField(db_column='usuario_creacion')),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='VentaTipoDePago',
            fields=[
                ('id_venta_tipo_pago', models.BigAutoField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField(db_column='monto')),
                ('id_tipo_pago', models.ForeignKey(db_column='id_tipo_pago', on_delete=django.db.models.deletion.DO_NOTHING, to='tipo_pago.tipopago')),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Venta Tipo de Pago',
                'verbose_name_plural': 'Ventas Tipos de Pago',
                'db_table': 'ventas_tipo_de_pago',
            },
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id_detalle', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_detalle', models.FloatField(db_column='total_detalle')),
                ('cantidad_producto', models.FloatField(db_column='cantidad_producto')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='productos.producto')),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Venta Detalle',
                'verbose_name_plural': 'Ventas Detalles',
                'db_table': 'venta_detalle',
            },
        ),
    ]
