# Generated by Django 3.2.16 on 2025-04-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadetalle',
            name='total_iva_10',
            field=models.FloatField(db_column='total_iva_10', default=0.0),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='total_iva_5',
            field=models.FloatField(db_column='total_iva_5', default=0.0),
        ),
    ]
