# Generated by Django 3.2.16 on 2025-09-24 15:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20250423_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVenta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Venta',
                'verbose_name_plural': 'Tipos de Ventas',
                'db_table': 'tipo_venta',
            },
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateTimeField(db_column='fecha_venta', default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='venta',
            name='id_tipo_venta',
            field=models.ForeignKey(blank=True, db_column='id_tipo_venta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.tipoventa'),
        ),
    ]
