# Generated by Django 5.2.9 on 2026-03-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_auto_20250924_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadetalle',
            name='precio_lista',
            field=models.FloatField(db_column='precio_lista', default=0.0),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='precio_unitario',
            field=models.FloatField(db_column='precio_unitario', default=0.0),
        ),
    ]
