# Generated by Django 5.2.9 on 2026-02-03 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0003_auto_20250924_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timbrado',
            fields=[
                ('id_timbrado', models.BigAutoField(primary_key=True, serialize=False)),
                ('nro_timbrado', models.BigIntegerField(db_column='nro_timbrado')),
                ('ruc', models.CharField(db_column='ruc', max_length=11)),
                ('fecha_inicio', models.DateTimeField(db_column='fecha_inicio')),
                ('fecha_fin', models.DateTimeField(db_column='fecha_fin')),
                ('nro_factura_desde', models.CharField(db_column='nro_factura_desde', max_length=15)),
                ('nro_factura_hasta', models.CharField(db_column='nro_factura_hasta', max_length=15)),
                ('usuario_creacion', models.BigIntegerField(db_column='usuario_creacion')),
            ],
            options={
                'verbose_name': 'Timbrado',
                'verbose_name_plural': 'Timbrados',
                'db_table': 'timbrado',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('nro_factura', models.CharField(db_column='nro_factura', max_length=15)),
                ('id_tipo', models.IntegerField(db_column='id_tipo')),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'factura',
            },
        ),
    ]
