# Generated by Django 3.2.16 on 2026-03-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='id_tipo',
            field=models.IntegerField(db_column='id_tipo', default=1),
        ),
        migrations.AlterField(
            model_name='factura',
            name='nro_factura',
            field=models.CharField(db_column='nro_factura', max_length=25, unique=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='tipo_factura',
            field=models.CharField(choices=[('CONTADO', 'Al contado'), ('CREDITO', 'Crédito')], default='CONTADO', max_length=10),
        ),
        migrations.AddField(
            model_name='factura',
            name='forma_pago',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('EMITIDA', 'Emitida'), ('ANULADA', 'Anulada')], default='EMITIDA', max_length=10),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateTimeField(auto_now_add=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='nombre_empresa',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='factura',
            name='ruc_empresa',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='factura',
            name='direccion_empresa',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='factura',
            name='nro_timbrado',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='factura',
            name='vigencia_timbrado_hasta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
