# Generated by Django 3.2.16 on 2026-03-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_factura_estado_y_datos_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
