# Generated by Django 3.2.16 on 2026-03-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0003_alter_factura_fecha_emision'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='vigencia_timbrado_desde',
            field=models.DateField(blank=True, null=True),
        ),
    ]
